[versions]
# Android & Kotlin
androidGradlePlugin = "9.2.1"
kotlin = "2.2.0"
kotlinMultiplatform = "2.2.0"

# AndroidX Libraries
activityCompose = "1.13.0"
coreKtx = "1.19.0"
navigationCompose = "2.9.2"

# Kotlin Libraries
coroutines = "1.10.2"
kotlinxSerialization = "1.9.0"
kotlinxDatetime = "0.5.0"

# KMP Libraries
sqldelight = "2.0.2"
koin = "4.0.1"
composeMultiplatform = "1.9.1"

detekt = "1.23.8"

[libraries]
# AndroidX Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# Compose (Android)
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Kotlin Libraries
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# KMP Libraries
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqldelight" }
sqldelight-driver-android = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqldelight" }
sqldelight-driver-ios = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqldelight" }
sqldelight-coroutines-extensions = { group = "app.cash.sqldelight", name = "coroutines-extensions", version.ref = "sqldelight" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }

[plugins]
# Android Plugins
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

# Kotlin Plugins
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# KMP Plugins
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinMultiplatform" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }

# Other Plugins
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
